name: Build and Publish

on:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
      
    - name: Dependencias
      run: dotnet restore ./MiNotSoSimpleApp/MiNotSoSimpleApp.csproj
      
    - name: Build
      run: dotnet build ./MiNotSoSimpleApp/MiNotSoSimpleApp.csproj --configuration Release

    - name: BuildTest
      run: dotnet build ./MiNotSoSimpleAppTests/MiNotSoSimpleAppTests.csproj 

    - name: RunTest
      run: dotnet test ./MiNotSoSimpleAppTests/MiNotSoSimpleAppTests.csproj

    - name: Publish
      run: dotnet publish ./MiNotSoSimpleApp/MiNotSoSimpleApp.csproj --configuration Release --output ./publish

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: ./publish
  
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: app
    - name: Output contents
      run: ls
    - name: Deploy to Server
      run: |
        echo "Deploy"
   
